version: "3.9"
services:

  blog_db:
    image: postgres:latest
    container_name: blog_db
    environment:
      POSTGRES_DB: "blog"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d blog" ]
      interval: 10s
      timeout: 5s
      retries: 5

  flask-blog:
    container_name: flaskapp
    build: .
    ports:
      - "8088:8088"
    command: bash -c "python create_db.py && python run.py"
    depends_on:
      blog_db:
        condition: service_healthy
